name: Deploy on VPS

on:
  push: 
    branches: [ "main" ]

jobs: 
  deploy: 

    runs-on: ubuntu-latest

    steps:
    - name: ssh deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          export NVM_DIR=/.nvm
          source ~/.nvm/nvm.sh
          cd /var/www/html/moovit
          git pull origin main
          npm i
          cd client && npm run build
          pm2 reload moovit
  

  
